### ISSUE TITLE
Environment and requirements.txt

### ISSUE THREAD

**Issue by tintindas** [mikeysan/search-imdb#4]
Setting up an environment and including a requirement.txt would make it easier to set up the project.

**Comment by mikeysan** [comment]
Thanks for the suggestion @tintindas. I'll add a requirements file now, actually.

**Comment by mikeysan** [comment]
Okay. That's done. 

Could you please elaborate on what environment setup you feel may be missing?

**Comment by tintindas** [comment]
Sorry, I confused this repo with one with similar issues. The requirements.txt is all that required attention here. Thanks!

**Comment by mikeysan** [comment]
Please read the readme again and see if it still makes sense. I have updated it as well.

**Comment by tintindas** [comment]
Yes! The setup process is much clearer now. 

The markdown code blocks have some weird spacing issues however that does not take anything away from the clarity of the readme.
